
name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          # this will also include README.md
          mkdir result
          echo "::set-output name=files::$(printf '"%s" ' *.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=result/result.docx ${{ steps.files_list.outputs.files }}
      - uses: actions/upload-artifact@master
        with:
          name: assets-for-download
          path: result
